name: Test gRPC Python Build
run-name: Test gRPC Python Build
on: [push]
jobs:
  setuptools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: apt update && sudo apt install libsystemd-dev python3-dev python3-venv -y

      - name: create venv
        run: python3 -m venv ./venv

      - name: install requirements
        run: source ./venv/bin/activate && pip install -r requirements.txt

      - name: ls -al
        run: ls -al

      - name: show pip freeze
        run: source ./venv/bin/activate && pip freeze

      - name: try to import Cython
        run: source ./venv/bin/activate && python3 -c "import Cython; print(Cython.__version__)" && pip --version

      - name: pip install .
        run: source ./venv/bin/activate && GRPC_PYTHON_BUILD_WITH_SYSTEMD=1 GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install .

  pyproject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: apt update && sudo apt install libsystemd-dev python3-dev python3-venv -y

      - name: create venv
        run: python3 -m venv ./venv

      - name: install requirements
        run: source ./venv/bin/activate && pip install uv && uv init && pip install -r requirements.txt

      - name: show pip freeze
        run: source ./venv/bin/activate && pip freeze

      - name: ls -al
        run: ls -al

      - name: show pyproject.toml
        run: cat pyproject.toml

      - name: try to import Cython
        run: source ./venv/bin/activate && python3 -c "import Cython; print(Cython.__version__)" && pip --version

      - name: pip install .
        run: source ./venv/bin/activate && GRPC_PYTHON_BUILD_WITH_SYSTEMD=1 GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install .

  pyproject-with-build-system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: apt update && sudo apt install libsystemd-dev python3-dev python3-venv -y

      - name: create venv
        run: python3 -m venv ./venv

      - name: install requirements
        run: source ./venv/bin/activate && pip install uv && uv init && pip install -r requirements.txt

      - name: show pip freeze
        run: source ./venv/bin/activate && pip freeze

      - name: ls -al
        run: ls -al

      - name: add build-system to pyproject.toml
        run: |
          echo '
          [build-system]
          requires = [
          "setuptools",
          "wheel>=0.29",
          "coverage>=4.0",
          "cython==3.1.1",
          "protobuf>=6.31.1,<7.0.0",
          "typing-extensions==4.12.2",
          ]
          ' >> pyproject.toml

      - name: show pyproject.toml
        run: cat pyproject.toml

      - name: try to import Cython
        run: source ./venv/bin/activate && python3 -c "import Cython; print(Cython.__version__)" && pip --version

      - name: pip install .
        run: source ./venv/bin/activate && GRPC_PYTHON_BUILD_WITH_SYSTEMD=1 GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install .
